### ISSUE TITLE
keypresses not detected

### ISSUE THREAD

**Issue by wonx** [dillbyrne/es-cec-input#4]
Hi, it's me again,
I managed to run the script without errors, but it is still unable to detect any keypresses from my tv remote, either in emulationstation or using the utility `evtest`. Maybe it's conflicting with the cec driver in Kodi, I don't know. Oh, I disabled that option to turn off the cec signal after closing Kodi that some other user suggested, but that didn't make a difference.

Anyway, that's what I do: after closing Kodi, I run the `es-cec-input.py` script (as the `pi` user), and then I run the `evtest` where I select the `python-uinput` option (the other is my bluetooth gamepad). And basically, it doesn't recognise any of the keypresses I do.

I haven't formally configured a keyboard in retropie. If I plug a keyboard, it just works fine to browse the menus and select games, but I don't know if that's enough to "configure it".

Also, I noticed that when the script is running at the same time as Kodi, the CPU usage increases by ~10% in a raspberry pi 2. I've disabled it from crontab until I figure out why.

I hope you can help me. It's not a big deal, but I think it's a good tool and I'd like to use it.

**Comment by dillbyrne** [comment]
Do you see output from your remote when you run `cec-client` ? 

This is what the script actually uses to get the input. You should see output when you press your remote buttons when cec-client is running.

Also try set up the keyboard using the menu in emulation station and pick something for all the buttons. I noticed your config in a previous issue didn't have something entered for the select button. As the script uses offsets it expects a certain number of buttons so try this first.

It shouldn't be using that much CPU.  I'm on a pi3 so that may be the difference.

You should not need to chance any kodi settings relating to cec. Only the setting to not turn your tv off when exiting kodi

**Comment by dillbyrne** [comment]
Closing as there was no reply. feel free to reopen if issue persists
