### ISSUE TITLE
Can't get CEC to work

### ISSUE THREAD

**Issue by mooooonbaby** [dillbyrne/es-cec-input#6]
Hi,

i've tried your script on retropie 4.2, but it doesn't work. maybe i misunderstood something here https://github.com/dillbyrne/es-cec-input. i can control retropie with my logitech controller and the keyboard. i've only mapped the cursors, enter and space to select and start and the buttons (key a to button a and so on).

the Dependencies are installed, the udev rule exists. the script is downloaded to the userdir and its executable. i connect to the pi with ssh and start the script. nothing happens, the cursor jumps to the next line, there is no new prompt. looks like it waiting for something :-) when i press a button on the tv remote nothing happens. there is no reaction on retropie or on the terminal window with the ssh connection. no error.

is there something wrong the way i set up the keyboard?

**Comment by dillbyrne** [comment]
Hi @mooooonbaby 

There should be no output from the script if it is working correctly. Try using your keyboard and mapping all the buttons with the retropie GUI, any keys will do, it just has to have one for each option 

The reason for this is that the script stores the mappings in a list and accesses them by index, so it is expecting them all to be set, so that they are in the correct places. Even though it only makes use of a few of them.

So try that first and reboot the pi and then let me know if it still does not work.

**Comment by mooooonbaby** [comment]
ok, now it works. for me it was hard to understand that i have to press the keys on the keyboard after starting the script.

there is a little input lag that i don't have when i use "normal" cec with kodi or libreelec (i have a dual boot system). is this normal?

**Comment by dillbyrne** [comment]
You don't have to press any keys on the keyboard after running the script provided your keyboard was set up properly, i.e. A key was chosen for all possible options. 

The apparent input lag is due to the action being applied when you release the key not when you press it. With my remote, acting when a key was presses resulted in double actions so I coded it to listen for key released instead. 

You can change https://github.com/dillbyrne/es-cec-input/blob/master/es-cec-input.py#L129

from `"released"` to `"pressed"` and see how you find that. Your remote may not respond in the the same way mine did.
