### ISSUE TITLE
CEC doesn't work when TV isn't powered on

### ISSUE THREAD

**Issue by mooooonbaby** [dillbyrne/es-cec-input#7]
When i start the tv and pi in that order es-cec-input works. but when i start the tv when the pi is already running cec doesn't work. when i start the script manually i have double inputs - that means in emulationstation menu it jumps not one point to left or right, it jumps two point in that direction. when the script isn't running nothings works.

i had this problem with not working cec when tv is powered on later than the pi also with libreelec. here it was enough to use the first hdmi port on the tv (it seems on some devices only the hdmi 1 fast a full cec support or something like that). but the pi is already connected to hdmi 1.

**Comment by dillbyrne** [comment]
That is a pi issue nothing to do with my script. My pi boots to kodi (which has its own cec implementation) and it won't work if it was turned on before the TV. If this happens I switch off and  unplug the TV for a second or two and then plug it in again. This causes the TV to send power down the hdmi line and it is detected on the pi and cec then  works. 

Your double input is due to the fact the script is already running ( but as cec is not active it can't relay get your instructions from the tv) and you're running another instance of it. 

It could be some power saving feature built into the pi chipset when the hdmi source is not active. That is my guess. Anyway I'm closing this issue as it is not due to the script

**Comment by mooooonbaby** [comment]
You unplug the hdmi cable from the tv or from the pi?

**Comment by dillbyrne** [comment]
I unplug the TV plug from the wall wait a few seconds and then plug it back in and then the pi detects it.

It is only necessary if the pi was on before the TV. if I turn on the TV and then the pi it works as expected.

another option is to ssh into the pi and reboot it
